<h1><center> About the NumPy 'random' package</center></h1>
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1200px-NumPy_logo.svg.png",width=300,height=60>

NumPy is the fundamental libray for scientific computing with Python. The random package found in the NumPy library is mainly used for generating/randomzing data. By looking at the package documentation [here](https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html) we can see the package is broken down into 4 sections.

* Simple random data 
* Permutations 
* Distributions
* Random generator
 
I will break this notebook into 4 sections based on these headings, showing and explaining examples of functions in each section.



<h1>Simple random data</h1>


<h3>Example #1 - numpy.random.rand</h3>

<i> Random values in a given shape.</i>



In [60]:
import numpy as np
np.random.rand(1,10,3)

array([[[0.84029885, 0.19185574, 0.01739428],
        [0.9924045 , 0.50328362, 0.87045766],
        [0.80653726, 0.87269791, 0.11642944],
        [0.60684598, 0.01621771, 0.74528227],
        [0.81069645, 0.41001964, 0.43235955],
        [0.56439466, 0.57476349, 0.4804882 ],
        [0.86106762, 0.57948951, 0.4623263 ],
        [0.49632418, 0.76005124, 0.24354422],
        [0.64576002, 0.30315041, 0.79405062],
        [0.11771446, 0.55785311, 0.63911559]]])

In this very basic example, we import the NumPy library and the random package so we can use them in our code. We then use the most basic function in the random package, 'rand'. This takes three arguments. The first two numbers are the range from which we want to generate random numbers. In our case, only numbers between 1 and 10 will be generated. The third argument dictates the dimensions of our array. In our case, i've chosen 3 to properly illustrate this point. 
 

It's important to remember different functions use different distributions to generate random numbers. In the above example, a uniform distribution is used.

<h3>Example #2 - numpy.random.randn</h3>

<i> Return a sample (or samples) from the “standard normal” distribution. </i>

In this example, we perform the same operation but instead use a <i>standard normal</i> or <i>Gaussian</i> distribution to generate the values. We will talk about distributions in more detail later on.

In [61]:
import numpy as np
np.random.randn(1,10,3)

array([[[-0.1990792 ,  0.65792357,  0.41282409],
        [-0.48630061, -0.51512903, -0.50881266],
        [-0.93321115, -0.60428332, -2.23403082],
        [-1.3266097 , -0.55926453,  0.02171916],
        [-0.47117156, -0.18611101, -1.6063825 ],
        [-0.87311173,  0.46594358,  0.62115523],
        [ 1.45783117, -0.95853307,  0.26037828],
        [-0.93613545,  0.77632281, -0.31548778],
        [ 0.68632546,  0.09534552,  1.33573608],
        [-1.37113474,  0.21223477,  0.28365342]]])

<h3>Example #3 - numpy.random.bytes</h3>

<i> Return random bytes. </i>


In this example, we simply call the np.random.bytes function and pass it a parameter which defines the number of random bytes to generate. In our example, we use 10 and a string with a length of 10 bytes is returned.


In [62]:
import numpy as np

np.random.bytes(10)

b'\xbed\xc8\x14\xf7\xbc\x00\xae\x97\xb7'

<h1>Permutations</h1>

In mathematics, the notion of permutation relates to the act of arranging all the members of a set into some sequence or order, or if the set is already ordered, rearranging (reordering) its elements, a process called permuting. There are only 2 functions in the permutations section. They are <i>shuffle</i> and <i>permutation</i>.

<h3>Example #1 - numpy.random.shuffle</h3>

<i> Modify a sequence in-place by shuffling its contents.</i>


In [63]:
arrangedArray = np.arange(1,21,1)
print(arrangedArray)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


First we create an array to shuffle. To properly demonstrate the shuffling, we will generate an array using <i>np.arrange</i>. This function is not included in the numpy random package. It returns an array of evenly spaced values. We can first declare the range with out first two parameters and the spacing with the 3rd parameter. Let's shuffle the array we just generated.

In [64]:
import numpy as np

# Create our arranged array like above
arrangedArray = np.arange(1,21,1)

# Shuffle the arranged array
np.random.shuffle(arrangedArray)

# Print the shuffled array
print(arrangedArray)

[ 2  4  1 16 17  8 18  9 20 11 14  3  5  7 15 19 10  6 12 13]


In the above example, we can see that the array is no longer arranged sequentially, but instead has been shuffled. It's important to remember this function only shuffles the array along the first axis of a multi-dimensional array. Let's see what I mean by this. 

In [65]:
import numpy as np

# Create our arranged array like above
arrangedArray = np.arange(1,10,1).reshape((3, 3))

# Shuffle the arranged array
np.random.shuffle(arrangedArray)

# Print the shuffled array
print(arrangedArray)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


Using the <i>reshape</i> function, we can reshapre our 1-dimensional array into a 3-dimensional one. Now can we see what we talked about above. Only the axis of the array was shuffled, not the contents of the array.

<h3>Example #2 - numpy.random.permutation</h3>

<i> Randomly permute a sequence, or return a permuted range.</i>



In [67]:
import numpy as np

np.random.permutation(10)

array([3, 2, 8, 7, 4, 9, 6, 1, 5, 0])

The function <i>np.random.permutation</i> works in a similar way to our above example such that it combines the operations of <i>np.arange</i> and <i>np.random.shuffle</i> into the same function. In the above example, we generate a 1-dimensional array of 10 numbers and permute them. There isn't much to say about this function except that it follows the same rules of only permuting the axis' of multi